### ISSUE TITLE
Performance Issue - Reconnecting Socket

### ISSUE THREAD

**Issue by icarusgd** [wavefrontHQ/wavefront-sdk-java#116]
Reconnecting socket poll timer is too frequent and not externally configurable. We are using wavefront-sdk in a cpu consumption sensitive environment. This flow alone consumes ~8% of our overall cpu consumption.

**Comment by icarusgd** [comment]
closed by mistake

**Comment by panghy** [comment]
This is currently done every 4 seconds, 8% of CPU seems very high, are just doing CPU sampling (which does not accurately measure CPU usage if the timer is just stuck on trying to read from the socket to make sure it's alive).
