### ISSUE TITLE
Error reporting points, respStatus=404 : keeps coming even though wavefrontSender.close is called

### ISSUE THREAD

**Issue by db-vmw** [wavefrontHQ/wavefront-sdk-java#120]
Hi,
I have followed the code as documented in  https://github.com/wavefrontHQ/wavefront-sdk-java . I'm using Direct Ingestion of metric (without proxy). The code works fine as long as the auth token used has the "Direct Ingestion" permission available. In case of the auth token doesn't have the required permission, the SDK keeps trying to send the metric infinitely. My expectation is that, when WavefrontSender.close() is called, the backend should stop trying to send the metric.

warning message details:

> 2020-01-27 17:05:59.296 [wavefrontDirectSender-0] WARN  com.wavefront.sdk.direct.ingestion.WavefrontDirectIngestionClient.internalFlush (363) - Error reporting points, respStatus=404
> 2020-01-27 17:05:59.833 [wavefrontDirectSender-0] WARN  com.wavefront.sdk.direct.ingestion.WavefrontDirectIngestionClient.internalFlush (363) - Error reporting points, respStatus=404

The above mentioned error message keeps printing in the log. 
Questions:

- How may I get ride of this error. i.e. Stop backend in retrying to send the metric?

- How may I catch the error so that, I can throw the error back to user to provide required privileges for the corresponding user in Wavefront (user associated with auth token)?

Thanks,
Dinesh

**Comment by panghy** [comment]
@hanwavefront can you take a look?

**Comment by panghy** [comment]
Seems like a 404 means it's wrong URL altogether but @hanwavefront can we also confirm that we are not sending traffic on close()

@sushantdewan123 please triage if ncessary

**Comment by hanwavefront** [comment]
@panghy Yes, as far as I can tell, 404 results from an invalid path.  Invalid token or invalid permissions now results in 401/403, for which we disable the sending of the entity.  Sending with a closed sender is now prevented and triggers an "attempt to send using closed sender" exception.

**Comment by db-vmw** [comment]
@panghy , @hanwavefront ,
Okay.  I have tried again and observed that, instance name with trailing "/" prints the warning message specified. (Ex: https://wavefront.com/).
I can handle this "/" in my code before wavefront SDK.
Can we please implement flush() method to return Boolean value indicating, if sending of all the metrics were successful? Issue here for me is, I will not even know if the sending of metric was successful. If not, can you please update the method to throw exception, which the wavefront SDK consumer can handle(may be by letting user to correct the input).
Because, If there is an issue in the input like tariling "/", how will even I know that sending of metric failed? 
Let me know if I can contribute to the code as well. 

Thanks,
Dinesh

**Comment by panghy** [comment]
I believe return true/false on flush() is not the right approach since typically it's too late already to catch these issues. To be clear, 404 means that it's talking to the wrong backend (you can put www.google.com and it would also 404). I also think that the latest builds should not balk on tailing "/" 

@MikeMcMahon please confirm.

We might want to also print the end point that we are trying instead of just saying 404 (since, well, if you did in fact flush to www.google.com, an error message that said **"Error reporting points to https://www.google.com/report, respStatus=404"** would be easier to understand why).

**Comment by MikeMcMahon** [comment]
> I believe return true/false on flush() is not the right approach since typically it's too late already to catch these issues. To be clear, 404 means that it's talking to the wrong backend (you can put [www.google.com](http://www.google.com) and it would also 404). I also think that the latest builds should not balk on tailing "/"
> 
> @MikeMcMahon please confirm.
> 
> We might want to also print the end point that we are trying instead of just saying 404 (since, well, if you did in fact flush to [www.google.com](http://www.google.com), an error message that said **"Error reporting points to https://www.google.com/report, respStatus=404"** would be easier to understand why).

correct, in the latest builds we do not talk directly on /

**Comment by panghy** [comment]
Okay, closing for now
