### ISSUE TITLE
Use semver like version scheme

### ISSUE THREAD

**Issue by snicoll** [wavefrontHQ/wavefront-sdk-java#138]
The current two digits version scheme is quite confusing as it's unusual to have maintenance releases as `2.1`, `2.2`, `2.3`. 

Please consider using `X.Y.Z` version numbering where `Z` denotes a patch release.

**Comment by snicoll** [comment]
Any update on this?

**Comment by akodali18** [comment]
This was fixed with https://github.com/wavefrontHQ/wavefront-sdk-java/pull/156
