### ISSUE TITLE
Rework build.version implementation

### ISSUE THREAD

**Issue by snicoll** [wavefrontHQ/wavefront-sdk-java#161]
In #156, the SDK now emits a metric with the version of the SDK. To identify the version of the SDK, it  reads a `build.properties` at the root of the classpath that contains a value provided by the build tool filtering resource.

Anyone could have a `build.properties` in their app that would clash with this file. And usually that sort of information should be stored in `META-INF`. 

A well known technique is to set the version in the `MANIFEST.MF` of the jar file and read it from there. See for instance what [the Spring Boot project does](https://github.com/spring-projects/spring-boot/blob/57539e016750899f1094a6eab7603db3ba48b46c/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringBootVersion.java#L45).

Although I understand SDK metrics have a dedicated prefix, I wonder if `version` [isn't a bit too generic](https://github.com/wavefrontHQ/wavefront-sdk-java/blob/4328c36190ccecd969dc8bc249b2895dc08c5c53/src/main/java/com/wavefront/sdk/common/clients/WavefrontClient.java#L271) and could use some sort of qualifier.

**Comment by akodali18** [comment]
This is fixed with https://github.com/wavefrontHQ/wavefront-sdk-java/pull/162
