### ISSUE TITLE
Introduce retry mechanism in Reporting service

### ISSUE THREAD

**Issue by karabadzhiys** [wavefrontHQ/wavefront-sdk-java#207]
At the moment Reporting service tries to [send the data once](https://github.com/wavefrontHQ/wavefront-sdk-java/blob/master/src/main/java/com/wavefront/sdk/common/clients/service/ReportingService.java#L61) without any retries. In cases when the WavefrontClient flushing period is too big and the buffer size is too low it will cause data points to be dropped. A potential good option is using retrying strategy based on [Exponential Backoff And Jitter](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/)

**Comment by oppegard** [comment]
Our retry mechanism is implemented in `WavefrontClient`, based on whether the HTTP status code returned by `ReportingService#send()` is considered retriable: https://github.com/wavefrontHQ/wavefront-sdk-java/blob/1608bef424508856716e27767ab9d4a4fd57d9b4/src/main/java/com/wavefront/sdk/common/clients/WavefrontClient.java#L733-L764

The flushing period and buffer size can be tuned to meet the needs of your specific application, as there isn't one size that fits all.

**Comment by karabadzhiys** [comment]
Thanks sounds good.
