### ISSUE TITLE
Unable to obtain status code from the Wavefront service error 

### ISSUE THREAD

**Issue by Paresh-patilpa** [wavefrontHQ/wavefront-sdk-java#214]
We are using following libraries in our spring application:
io.micrometer.registry.wavefront.version 1.5.14
com.wavefront.opentracing.sdk.version 1.13

Spring boot starter version - 2.3.12.RELEASE
Spring boot - 5.2.15.RELEASE
proxy - v10.07
Java version - Java 11

Facing following error: 
```
Unable to obtain status code from the Wavefront service at http://wavefront-proxy:2878/report?f=wavefront

java.net.SocketTimeoutException: Read timed out
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
... //
at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
... //
at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
at com.wavefront.sdk.common.clients.service.ReportingService.send(ReportingService.java:64)
... 11 common frames omitted
```

We tried to  upgrade wavefront-opentracing-sdk-java dependency to 2.1.7
But then application start up failed with 
```
An attempt was made to call a method that does not exist. The attempt was made from the following location:

com.wavefront.internal.reporter.WavefrontInternalReporter$Builder.<init>(WavefrontInternalReporter.java:84)

The following method did not exist:

'com.wavefront.sdk.common.Namea0ab145dff com.wavefront.sdk.common.Namebe09ab128e

```

Would you please help in identifying the compatible version of com.wavefront.opentracing.sdk.version for the given Spring boot  application.

**Comment by oppegard** [comment]
Hi @Paresh-patilpa, can you give us the `pom.xml` of this application (or a redacted one)? That will enable us to better understand the exact dependency chain going on.

**Comment by Paresh-patilpa** [comment]
Hi @oppegard  
Thanks for looking into this.

[pomxml.txt](https://github.com/wavefrontHQ/wavefront-sdk-java/files/7553022/pomxml.txt)
This is a redacted version.

**Comment by oppegard** [comment]
The file you attached doesn't have `wavefront-sdk-java` as a dependency, nor any `opentracing` dependencies as reported by `mvn dependency:list`.

Your original issue concerns the `Unable to obtain status code` message. You need to be using `wavefront-sdk-java` 2.6.3 or later, which contains this PR to supress that message unless it repeats 5 times: https://github.com/wavefrontHQ/wavefront-sdk-java/pull/168.

**Comment by Paresh-patilpa** [comment]
Thanks Glenn. I must have removed it as part of sensitive dependencies. This one has the relevant dependencies.  
[pomxml.txt](https://github.com/wavefrontHQ/wavefront-sdk-java/files/7560060/pomxml.txt)


Note that we are using `com.wavefront.opentracing.sdk`. What version should we use that has changes to suppress that error  log. 
OR 
Do you recommend to use  `wavefront-sdk-java` (2.6.3)  instead of  `com.wavefront.opentracing.sdk`.

**Comment by Paresh-patilpa** [comment]
I got to know that  `wavefront-sdk-java`  2.2. is being used as transitive dependency coming from `io.micrometer:micrometer-registry-wavefront`  1.5.1 . 

micrometer-registry-wavefront 1.6.10 contains 2.6.4 version of wavefront-sdk-java. I will try using that.

**Comment by oppegard** [comment]
@Paresh-patilpa could you try upgrading to micrometer-registry-wavefront 1.8.0: https://search.maven.org/artifact/io.micrometer/micrometer-registry-wavefront/1.8.0/jar

It includes wavefront-sdk-java 3.0.0. If that doesn't work for some reason, try micrometer-registry-wavefront 1.6.10 instead.

**Comment by Paresh-patilpa** [comment]
@oppegard upgrading to micrometer-registry-wavefront 1.8.0 helped. 
Thanks a lot!
