### ISSUE TITLE
Allow SDK runtime monitoring

### ISSUE THREAD

**Issue by ankurdh** [wavefrontHQ/wavefront-sdk-java#76]
It would be good to have these for monitoring:

- Buffer fullness
- Flush Rate
- Data Ingestion Rate
- Points sent
- Points dropped

There is no feedback about any of these from the SDK to the client using it. This makes it all the more important.

**Comment by sushantdewan123** [comment]
Do you want all those to be reported to Wavefront as metrics?

**Comment by hanwavefront** [comment]
@ankurdh Thank you for the feedback. We will be releasing a new version of the SDK within the next two days that adds internal diagnostic metrics.
