### ISSUE TITLE
Potential Data Loss when Using Direct Ingestion

### ISSUE THREAD

**Issue by ankurdh** [wavefrontHQ/wavefront-sdk-java#77]
Ref 1: https://github.com/wavefrontHQ/wavefront-sdk-java/blob/master/src/main/java/com/wavefront/sdk/direct/ingestion/WavefrontDirectIngestionClient.java#L185

```java
private void internalFlush(LinkedBlockingQueue<String> buffer, String format)
      throws IOException {
    ...
    ...
    try (InputStream is = batchToStream(batch)) {
      // Exception in the below line will not add the data back to buffer
      int statusCode = directService.report(format, is); 
      if (400 <= statusCode && statusCode <= 599) {
        logger.log(Level.WARNING, "Error reporting points, respStatus=" + statusCode);
        try {
          buffer.addAll(batch);
        } catch (Exception ex) {
          // unlike offer(), addAll adds partially and throws an exception if buffer full
          logger.log(Level.WARNING, "Buffer full, dropping attempted points");
        }
      }
    } catch (IOException ex) {
      failures.incrementAndGet();
      throw ex;
    }
  }
```
If an exception is thrown by `directService.report()`, then we don't know if the data write failed or we failed to get the http return code from the URL Output stream.

Ref 2: https://github.com/wavefrontHQ/wavefront-sdk-java/blob/master/src/main/java/com/wavefront/sdk/direct/ingestion/DataIngesterService.java#L54

```java
try (GZIPOutputStream gzipOS = new GZIPOutputStream(urlConn.getOutputStream())) {
        byte[] buffer = new byte[4096];
        while (stream.available() > 0) {
          gzipOS.write(buffer, 0, stream.read(buffer));
        }
        gzipOS.flush();
      }
      statusCode = urlConn.getResponseCode();
      readAndClose(urlConn.getInputStream());
    } catch (IOException ex) {
      if (urlConn != null) {
        statusCode = urlConn.getResponseCode();
        readAndClose(urlConn.getErrorStream());
      }
    }
```

I was testing the direct Ingestion and I noticed that intermittently a `java.net.SocketTimeoutException: Read timed out` was thrown with this stack:
```
java.net.SocketTimeoutException: Read timed out
	at com.wavefront.sdk.direct.ingestion.DataIngesterService.report(DataIngesterService.java:58)
	at com.wavefront.sdk.direct.ingestion.WavefrontDirectIngestionClient.internalFlush(WavefrontDirectIngestionClient.java:185)
	at com.wavefront.sdk.direct.ingestion.WavefrontDirectIngestionClient.flush(WavefrontDirectIngestionClient.java:171)
	at com.wavefront.sdk.direct.ingestion.WavefrontDirectIngestionClient.run(WavefrontDirectIngestionClient.java:163)
```

The exception here occurs when we try to get the `responseCode`. But the method `DataIngesterService.report` can also throw an exception when doing a `gzipOS.write` or `gzipOS.flush` and subsequently we might get an exception inside the `catch` block. In this case, we cascade the exception to `WavefrontDirectIngestionClient.report()` and we never add the data back to buffer for retrying.

**Comment by panghy** [comment]
@basilisk487 or @MikeMcMahon is this obsolete?

**Comment by basilisk487** [comment]
@panghy @MikeMcMahon Looks like this bug is still valid, ReportingService.send still can throw an IOException if it happens in the catch (IOException) block.

**Comment by panghy** [comment]
okay, assigned to you two then

**Comment by MikeMcMahon** [comment]
the outermost exception handling simply drops the points; we can call to re-queue the points there so that any exception during the processing (regardless of source) will cause points to be resent later, since it would become impossible to know if the points were actually received if we cannot obtain the status code.

**Comment by MikeMcMahon** [comment]
```java
      } catch (IOException ex) {
        requeue(buffer, items, dropped, entityType, bufferFullMessageType);
        reportErrors.inc();
        for (int j = i + 1; j < batch.size(); j++) {
          dropped.inc(batch.get(j).size());
        }
        throw ex;
      }
```

vs. just dropping the points completely.

**Comment by MikeMcMahon** [comment]
hrm actually this looks like we can drop an entire batch not just the points being sent, we should adjust the service code to return a -1 and safely attempt to close the stream if we detect an error.   We could overflow the buffer and begin dropping points that way, but that might be preferred here (since we'd eventually get those points vs. losing them completely when the network comes back)

**Comment by MikeMcMahon** [comment]
fix is in master
